### PR TITLE
include sender id in findnode, fix tests

### LINKED ISSUE #28: Rewrite grcp_mock so it does not use the server
the grpc mock should only mock grpc functionality.

### PR DESCRIPTION
**Pull request by Kyrne**
make sure the sender node is not included in response, fix server tests. closes #28

### CODE REVIEW

File: internal/server/server.go [hunk 1]
```diff
@@ -76,9 +76,8 @@ func (s *Server) Ping(ctx context.Context, sender *pb.Node) (*pb.Node, error) {
 	}, nil
 }
 
-func (s *Server) FindNode(ctx context.Context, kademliaID *pb.KademliaID) (*pb.Nodes, error) {
-	// TODO this needs to make sure that sender node and itself is not included in response
-	candidates := s.routingTable.FindClosestContacts((*kademliaid.KademliaID)(kademliaID.Value), env.BucketSize)
+func (s *Server) FindNode(ctx context.Context, request *pb.FindNodeRequest) (*pb.Nodes, error) {
+	candidates := s.routingTable.FindClosestContacts((*kademliaid.KademliaID)(request.Target.Value), (*kademliaid.KademliaID)(request.Sender.Value), env.BucketSize)
```
Comment (maxluetkemeyer) [inline internal/server/server.go:80]: 1. This is hard to read.
2. It is not very intuitive, if we have our own in the contact list. Because we need to have smth. like a "blacklist" attribute, which is not nice.
