### PR TITLE
Add a timeout to bootstrap instead of waiting a fixed delay.

### LINKED ISSUE #42: Implement timeout to bootstraping instead of waiting a fixed delay
Right now, the program waits 5 seconds before initializing the bootstrap to wait for the docker network to boot up.

A more efficient solution would be to loop the bootstrapping until we have a valid contact; with a timeout.

### PR DESCRIPTION
**Pull request by hugocornago-ltu**
Tested by changing to `replicas: 1` in `docker-compose.yml`.

PD: also experimenting with [slog](https://pkg.go.dev/golang.org/x/exp/slog), the default structured logging solution provided by golang.

closes #42

### CODE REVIEW

File: env/env.go [hunk 1]
```diff
@@ -15,6 +16,8 @@ var BucketSize = 20 // must be larger than 0
 var NodesProxyDomain = "kademlianodes"
 var Alpha = 3 // degree of parallelism
 var RPCTimeout = 5 * time.Second
+var BootstrapTimeout = 10 * time.Second
+var Debug = true
```
Comment (maxluetkemeyer) [inline env/env.go:20]: Debug should be accessible via env variables

File: internal/node/node.go [hunk 2]
```diff
@@ -35,38 +36,52 @@ func New(client network.ClientRPC, routingTable *routingtable.RoutingTable, stor
...
-	log.Printf("addresses:%v\n", addresses)
+		ourAddress := n.RoutingTable.Me().Address
+		ips = removeAddress(ips, ourAddress)
+
+		logger := logger.With(slog.Any("ips", ips))
+
+		logger.Debug("pinging")
+
+		recipient, err = n.pingIPsAndGetContact(ctx, ips)
+		if err != nil {
```
Comment (maxluetkemeyer) [inline internal/node/node.go:64]: Please use guard clauses (change if to err == nil and restructure code)

File: internal/node/node.go [hunk 3]
```diff
@@ -92,3 +107,17 @@ func (n *Node) pingIPsAndGetContact(ctx context.Context, targetIPs []string) (*c
 
 	return nil, fmt.Errorf("unable to ping any contacts")
 }
+
+func removeAddress(ips []string, addressToRemove string) []string {
+	ipToRemove := addressToRemove[:len(addressToRemove)-6]
```
Comment (maxluetkemeyer) [inline internal/node/node.go:112]: Why is here a "-6"

**Review by maxluetkemeyer — CHANGES_REQUESTED** [review]
Please address comments
